### ISSUE TITLE
[Question] Dynamic phpdoc - is it possible?

### ISSUE THREAD

**Issue by nikoladsp** [drupol/DynamicObjects#3]
Hi,
I am looking for a library that can create classes with properties and phpdoc to create classes dynamically. Is it possible that this library support this, or if not - can you please point me how to do this myself.

Thank you in advance.

Kindest regards

**Comment by drupol** [comment]
Hello,

This is not possible with this library. If you're looking for a library to generate PHP Classes, you may use [Nikic's PHP Parser](https://github.com/nikic/PHP-Parser) or [Laminas Code](https://github.com/laminas/laminas-code).

Good luck :)

**Comment by nikoladsp** [comment]
Thank you very much!
